FROM golang:1.24.2-alpine3.21

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download the dependencies
RUN go mod download
RUN go mod tidy
RUN go mod vendor

# Copy the source code
COPY . .

# Build the application
RUN go build

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["./MobileAppProject"]