version: "3.9"
name: "SweetSpot"

services:
  app:
    build: .
    image: sweetspot:latest
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "8000:${PORT}"
    depends_on:
      - redis
    command: [ "./MobileAppProject" ]
    container_name: "SweetSpot"
    environment:
      - REDIS_ADDRESS=redis
  redis:
    image: redis:8.0-rc1-alpine3.21
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "6380:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  redis_data: